[package]
name = "mountpoint-s3-macros"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.27"
syn = { version = "2.0.16", features = ["extra-traits", "full"] }