name: Integration tests (mainline)

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name:
    uses: ./.github/workflows/integration.yml
    with:
      environment: Mainline integration tests
      ref: ${{ github.event.ref }}