name: Integration tests (PR)

on:
  pull_request_target:
    branches: [ "main" ]

jobs:
  integration:
    name: Integration
    uses: ./.github/workflows/integration.yml
    with:
      environment: PR integration tests
      ref: ${{ github.event.pull_request.head.sha }}
