name: Integration tests (PR)

on:
  pull_request_target:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    uses: ./.github/workflows/integration.yml
    with:
      environment: PR integration tests